version: '3'

services:
  apollo:
    build:
      context: .
      dockerfile: Dockerfile
    image: apollo:latest
    container_name: apollo
    restart: always
    ports:
      - 127.0.0.1:8000:80
