version: '3'

services:
  apollo:
    build:
      context: .
      dockerfile: Dockerfile
    image: apollo:latest
    container_name: apollo
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:www.arielmiki.com"
      - "traefik.port=80"
      - "traefik.frontend.protocol=https"

networks:
  web:
    external: true